---
title: "static"
format: html
editor: visual
---


Loading needed libraries
```{r}
library(tidyverse)
library(janitor)
library(knitr)
```

Source Pages
```{r}
source("helper.R")
```


Loading data
```{r}
df_raw <- read_csv("user_behavior_dataset.csv")
```
Making df nice (also on helper page)
```{r}
df <- df_raw|>
  mutate(across(where(is.character), as.factor)) |> 
  mutate(`User Behavior Class` = 
           factor(x = `User Behavior Class`, 
                  labels = c("Light Usage", "Mild Usage", "Moderate Usage", "Heavy Usage", "Extreme Usage"))) |>
  clean_names()
```


Calling 1-way tables
```{r}
cat <- df |> select(where(is.factor))
for(i in 1:length(cat)){
  print(make_way_tables(cat, names(cat)[i]))
  }
```

Calling A 2 way table
```{r}
make_way_tables(cat, c("device_model", "gender"))
```

Making filtered table
```{r}
make_filtered_tables(df, c("age", "number_of_apps_installed"), conds = (as.numeric(df$user_behavior_class) < 3 & df$age > 50), groups =c( "device_model", "gender"))

```

Make numeric summaries
```{r}
make_summaries(df, c("age", "number_of_apps_installed"), groups =c("device_model", "gender"))
```


Make graphs one of each
types = bar, density, box, jitter, scatter, correlation 
```{r}
make_visuals(df, "gender", type = bar)
make_visuals(df, "gender", group = "device_model", type = bar)

make_visuals(df, "age", type = "density")
make_visuals(df, "age", group = "gender", type = "density")

make_visuals(df, "age", type = "box")
make_visuals(df, "age", group = "device_model", type = "box")

make_visuals(df, "age", group = "device_model", type = "jitter")

make_visuals(df, vars = c("age", "number_of_apps_installed"), type = "scatter")
make_visuals(df, vars = c("age", "number_of_apps_installed"), group = "device_model", type = "scatter")

make_visuals(df, names(df), type = "correlation")

```

